# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GameWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(404, 305)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 401, 301))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.giveup_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.giveup_button.sizePolicy().hasHeightForWidth())
        self.giveup_button.setSizePolicy(sizePolicy)
        self.giveup_button.setObjectName("giveup_button")
        self.gridLayout.addWidget(self.giveup_button, 10, 0, 1, 1)
        self.round_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.round_label.setFont(font)
        self.round_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.round_label.setAlignment(QtCore.Qt.AlignCenter)
        self.round_label.setObjectName("round_label")
        self.gridLayout.addWidget(self.round_label, 0, 0, 1, 2)
        self.submit_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.submit_button.sizePolicy().hasHeightForWidth())
        self.submit_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStrikeOut(False)
        font.setKerning(True)
        self.submit_button.setFont(font)
        self.submit_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.submit_button.setCheckable(False)
        self.submit_button.setFlat(False)
        self.submit_button.setObjectName("submit_button")
        self.gridLayout.addWidget(self.submit_button, 10, 1, 1, 1)
        self.question_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.question_label.setFont(font)
        self.question_label.setAlignment(QtCore.Qt.AlignCenter)
        self.question_label.setObjectName("question_label")
        self.gridLayout.addWidget(self.question_label, 2, 0, 1, 2)
        self.freezetime_button = QtWidgets.QPushButton(self.gridLayoutWidget)

        freezetime_icon = QIcon('assets/freezetime_icon.png') # import picture
        self.freezetime_button.setObjectName("freezetime_button")
        self.freezetime_button.setIcon(freezetime_icon) # add freezetime icon

        self.gridLayout.addWidget(self.freezetime_button, 3, 1, 1, 1)
        self.skip_total_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.skip_total_label.setAlignment(QtCore.Qt.AlignCenter)
        self.skip_total_label.setObjectName("skip_total_label")
        self.gridLayout.addWidget(self.skip_total_label, 8, 1, 1, 1)
        self.answer_c = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.answer_c.setFont(font)
        self.answer_c.setObjectName("answer_c")
        self.gridLayout.addWidget(self.answer_c, 7, 0, 2, 1)
        self.doublepoint_button = QtWidgets.QPushButton(self.gridLayoutWidget)

        doublepoint_icon = QIcon('assets/doublepoint_icon.png') # import picture
        self.doublepoint_button.setObjectName("doublepoint_button")
        self.doublepoint_button.setIcon(doublepoint_icon) # add double point icon

        self.gridLayout.addWidget(self.doublepoint_button, 5, 1, 1, 1)
        self.timer_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.timer_label.setFont(font)
        self.timer_label.setAlignment(QtCore.Qt.AlignCenter)
        self.timer_label.setObjectName("timer_label")
        self.gridLayout.addWidget(self.timer_label, 1, 0, 1, 2)
        self.freezetime_total_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.freezetime_total_label.setAlignment(QtCore.Qt.AlignCenter)
        self.freezetime_total_label.setObjectName("freezetime_total_label")
        self.gridLayout.addWidget(self.freezetime_total_label, 4, 1, 1, 1)
        self.skip_button = QtWidgets.QPushButton(self.gridLayoutWidget)

        skip_icon = QIcon('assets/skip_icon.png') # import picture
        self.skip_button.setObjectName("skip_button")
        self.skip_button.setIcon(skip_icon) # add skip icon

        self.gridLayout.addWidget(self.skip_button, 7, 1, 1, 1)
        self.spacer = QtWidgets.QLabel(self.gridLayoutWidget)
        self.spacer.setText("")
        self.spacer.setObjectName("spacer")
        self.gridLayout.addWidget(self.spacer, 9, 0, 1, 2)
        self.answer_b = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.answer_b.setFont(font)
        self.answer_b.setObjectName("answer_b")
        self.gridLayout.addWidget(self.answer_b, 5, 0, 2, 1)
        self.answer_a = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.answer_a.setFont(font)
        self.answer_a.setObjectName("answer_a")
        self.gridLayout.addWidget(self.answer_a, 3, 0, 2, 1)
        self.doublepoint_total_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.doublepoint_total_label.setAlignment(QtCore.Qt.AlignCenter)
        self.doublepoint_total_label.setObjectName("doublepoint_total_label")
        self.gridLayout.addWidget(self.doublepoint_total_label, 6, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.giveup_button.setText(_translate("Form", "Give up"))
        self.round_label.setText(_translate("Form", "Round: {round}"))
        self.submit_button.setText(_translate("Form", "Submit"))
        self.question_label.setText(_translate("Form", "20 : 2 ="))
        self.freezetime_button.setText(_translate("Form", " Freeze Time"))
        self.skip_total_label.setText(_translate("Form", "You Have : {total}"))
        self.answer_c.setText(_translate("Form", "10"))
        self.doublepoint_button.setText(_translate("Form", " Double Point"))
        self.timer_label.setText(_translate("Form", "{timer}"))
        self.freezetime_total_label.setText(_translate("Form", "You Have : {total}"))
        self.skip_button.setText(_translate("Form", " Skip"))
        self.answer_b.setText(_translate("Form", "10"))
        self.answer_a.setText(_translate("Form", "10"))
        self.doublepoint_total_label.setText(_translate("Form", "You Have : {total}"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
